# Generated by Django 3.0.5 on 2020-07-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=200)),
                ('confirmed_cases', models.IntegerField(default=0)),
                ('active_cases', models.IntegerField(default=0)),
                ('dead_cases', models.IntegerField(default=0)),
                ('recovered_cases', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=200)),
                ('confirmed_cases', models.IntegerField(default=0)),
                ('active_cases', models.IntegerField(default=0)),
                ('dead_cases', models.IntegerField(default=0)),
                ('recovered_cases', models.IntegerField(default=0)),
            ],
        ),
    ]
