# Generated by Django 3.0.5 on 2020-07-11 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
